### ISSUE TITLE
Fitur Export File / Print Menampilkan 500 | Server Error, data tidak tampil (Absensi Online Laravel)

### ISSUE THREAD

**Issue by pyxsor** [sandyh90/Codeigniter3-absen-digital#11]
Fitur Export File / Print Menampilkan 500 | Server Error, data tidak tampil

![image](https://user-images.githubusercontent.com/57718999/155065734-8e660965-72ea-4c33-978c-607d8ebc0ffe.png)

**Comment by pyxsor** [comment]
+ Kesalahan saat Menambah User Menggunakan fitur Tambah User

![image](https://user-images.githubusercontent.com/57718999/155063915-d3fdaa5f-e8f4-4c5c-b123-3d71e245389a.png)

**Comment by pyxsor** [comment]
- Kesalahan saat Import User data menggunakan Excel 2007 - Terbaru (Setelah import, tanpa konfirmasi text/ menghilang dan tidak ada perubahan apa-apa)

![image](https://user-images.githubusercontent.com/57718999/155065319-abd095c1-2a37-4b77-aeb1-ddd69eed3fbe.png)

**Comment by sandyh90** [comment]
Coba mas di bagian file ".env" ubah bagian **APP_DEBUG=true** nah terus coba mas tracking errornya, untuk yang ajax coba cek ke inspect terus ke menu network dan coba jalankan kembali untuk yang ajaxnya

**Comment by pyxsor** [comment]
Bingung mas hehe

https://flareapp.io/share/OmVKkOxP
https://flareapp.io/share/o7AnM2j5
https://flareapp.io/share/V7jNwAJ7

sama yang fitur penambahan user by tombol dan import excell , ndak keluar hasil debug/report error nya mas

**Comment by pyxsor** [comment]
Bingung mas hehe

https://flareapp.io/share/OmVKkOxP
https://flareapp.io/share/o7AnM2j5
https://flareapp.io/share/V7jNwAJ7

![image](https://user-images.githubusercontent.com/57718999/155086512-2c64187e-8c43-4d97-ad48-5d847681cfd8.png)

sama yang fitur penambahan user by tombol dan import excell , ndak keluar hasil debug/report error nya mas

![image](https://user-images.githubusercontent.com/57718999/155087302-7e1af8a3-9bfe-4201-aacf-a348a3f6f4ed.png)

**Comment by sandyh90** [comment]
@pyxsor Kalau untuk yang sharelink ini
https://flareapp.io/share/OmVKkOxP
https://flareapp.io/share/o7AnM2j5
https://flareapp.io/share/V7jNwAJ7
Itu ada permasalahan di **ob_clean()** nya mas coba dihapus saja yang ada ob_clean() nya

Nah untuk yang error di fitur ajax bagian yang 500 itu coba di buka bagian preview

**Comment by pyxsor** [comment]
![image](https://user-images.githubusercontent.com/57718999/155088511-7772e8b2-4138-4552-a202-e0db731fd911.png)

Sudah bisa untuk fitur cetaknya mas, terima kasih banyak atas bantuannya.

**Comment by sandyh90** [comment]
> ![image](https://user-images.githubusercontent.com/57718999/155088511-7772e8b2-4138-4552-a202-e0db731fd911.png)
> 
> Sudah bisa untuk fitur cetaknya mas, terima kasih banyak atas bantuannya.

Mantap mas kalau sudah bisa, untuk yang ajax add user by button dan import gimana mas masih bermasalah atau tidak?

**Comment by pyxsor** [comment]
![image](https://user-images.githubusercontent.com/57718999/155103331-fa2a4747-9341-4dcb-8938-0455f30d7424.png)
![image](https://user-images.githubusercontent.com/57718999/155104803-27c21473-8307-4904-8a61-abd2953238d9.png)


Masih error mas

**Comment by sandyh90** [comment]
oh kalau itu permasalahnnya karena **"is_email_verify"** nya tidak ada nilai defaultnya jadi error coba mas di bagian migrasinya
diubah seperti gambar ini

tempatnya filenya ada di **"database/migrations/2014_10_12_000000_create_users_table.php"**

```
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique()->nullable();
            $table->string('username')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->text('user_employee_position');
            $table->string('user_employee_code', 30)->nullable();
            $table->text('user_photo');
            $table->text('user_qrcode_img');
            $table->tinyInteger('user_age');
            $table->string('user_birthplace', 255);
            $table->date('user_birthday');
            $table->enum('user_gender', ['male', 'female']);
            $table->enum('user_work_type', ['fulltime', 'shift', 'parttime']);
            $table->enum('role_access', ['administrator', 'manager', 'moderator', 'employee']);
            $table->rememberToken();
            $table->boolean('use_qrcode')->default(FALSE);
            $table->boolean('is_active')->default(FALSE);
            $table->boolean('is_email_verify')->default(FALSE);
            $table->uuid('user_idcode');
            $table->dateTime('last_login')->nullable();
            $table->timestamps();
        });
    }
```

![Screenshot 2022-02-22 164744](https://user-images.githubusercontent.com/30236529/155106628-6da7d7cb-ba81-4755-9228-b0a2d8317c78.png)
h

setelah itu di **"php artisan migrate:fresh --seed"** dan itu otomatis melakukan seeding

**Comment by pyxsor** [comment]
![image](https://user-images.githubusercontent.com/57718999/155146951-09cdfb0f-f9e5-43d3-acdc-d116b418eb21.png)

Wah terima kasih banyakkk ya mas, sudah bisa semua kendala diatas,

Doa baik untuk orang baik 🙏

**Comment by sandyh90** [comment]
Siap sama sama mas terima kasih atas doanya dan senang membantu juga 😄🙏🏻
