### ISSUE TITLE
combined with a fingerprint machine is it possible?

### ISSUE THREAD

**Issue by fhariqaulady03** [sandyh90/Codeigniter3-absen-digital#3]
hi. Can you combine your application with a fingerprint engine?
if you want I'm ready to help development.
now I am developing a fingerprint engine program using php, but not using any framework. if you are interested let's develop it

**Comment by sandyh90** [comment]
Sorry for late respond, it's great idea but for now i'm not want to combined the app with fingerprint machine because this app framework library is too old and maybe some fingerprint machine can't work with old library. Thank for your idea before. 😄
