### ISSUE TITLE
Menambah kolom/tabel absen

### ISSUE THREAD

**Issue by ayahaceh** [sandyh90/Codeigniter3-absen-digital#4]
Saat melakukan Absen, setelah klik tombol absen, yang terjadi adalah muncul Sweet Alert! ini keren! Aplikasinya jg ringan dan codingannya juga rapi terstruktur.

Saya ingin menggunakan Absensi ini, tapi bagaimana jika setelah di klik Absen, yg muncul adalah halaman atau modal Form pengisian (penambahan kolom pada tabel absen), bagaimana cara melakukan ini? Bagian mana saja yang harus saya ubah untuk ini?

Khusus saat absen pulang, sy ingin menambah 2 kolom lagi :
1. Pekerjaan yang dilaksanakan [pekerjaan -> text]
2. Output yang dihasilkan [output -> text]

Pertanyaannya, Untuk kebutuhan diatas :
1. lbh baik bikin tabel baru "tb_pekerjaan_harian" dgn relasi id_absen, atau lbh baik tambahkan kolom di tabel "db_absensi" aja langsung?
2. Pada Model, model apa aja, dan dibagian mana saja yang harus saya perhatikan?
3. Pada Controller, Contr mana saja dan bagian mana saja yang harus sy perhatikan?
4. Pada bagian helper apa ada yang harus saya modif ulang?

Mohon petunjuknya, biar saya ga salah modif.
Terimakasih banyak sebelumnya!

**Comment by sandyh90** [comment]
Untuk pertanyaan mas tentang modifikasi sistem absennya boleh dicoba dengan cara seperti ini

1. Untuk yang tabel kalau menurut saya di tambahkan saja pada kolom "db_absensi" tidak perlu membuat yang baru tetapi kalau memang ingin dipisah boleh kemungkinan nanti pakainya sistem join atau menggunakan relasi "**id_absen**"

2. Untuk model yang diperhatikan itu bagian "**M_Front**" setelah itu ada dibagian `public function do_absen()`

3. Untuk controller yang di perhatikan bagian 

- "**Ajax.php**" yaitu pada dibagian `public function ​absenajax()` untuk fungsi pada absen dan juga `public function dataabs()` pada bagian type `$typesend == 'viewabs'` untuk jaga² kalau view modal absennya mau diubah

Untuk ubah modal pada **View Absensinya** ke directory `views/layout/dataabsensi` ada file yaitu **viewabsensi.php** dan silakan di modif pada bagian ini

```
<div class="row detail">
<div class="col-md-10 col-sm-8 col-6">
<dl class="row">
 <dt class="col-sm-5">Nama Pegawai:</dt> <dd class="col-sm-7"><?= $dataabsensi['nama_pegawai'] ?></dd> 
<dt class="col-sm-5">Tanggal Absen:</dt> <dd class="col-sm-7"><?= $dataabsensi['tgl_absen'] ?></dd>
 <dt class="col-sm-5">Waktu Datang:</dt> <dd class="col-sm-7"><?= $dataabsensi['jam_masuk'] ?></dd>
 <dt class="col-sm-5">Waktu Pulang:</dt> <dd class="col-sm-7"><?= (empty($dataabsensi['jam_pulang'])) ? 'Belum Absen Pulang' : $dataabsensi['jam_pulang']; ?></dd> 
<dt class="col-sm-5">Status Kehadiran:</dt> <dd class="col-sm-7"><?= ($dataabsensi['status_pegawai'] == 1) ? '<span class="badge badge-success">Sudah Absen</span>' : (($dataabsensi['status_pegawai'] == 2) ? '<span class="badge badge-danger">Absen Terlambat</span>' : '<span class="badge badge-primary">Belum Absen</span>'); ?></dd> 
<dt class="col-sm-5">Keterangan Absen:</dt> <dd class="col-sm-7"><?= $dataabsensi['keterangan_absen'] ?></dd> 
</dl> 
</div>
</div>
```

-  "**Docs.php**" untuk yang export _**EXCEL**_  silakan modif bagian ini untuk disesuaikan

```
/**
* Untuk mergeCellsnya jangan lupa di ubah 
* lagi setelah ada penambahka kolom biar
* terlihat rapih untuk kolomnya pada headernya
*/

$sheet->setCellValue('A1', 'Rekap Data Absensi: ' . $dataapp['nama_instansi'] . ''); 
$sheet->mergeCells('A1:H2'); 
$sheet->getStyle('A1')->applyFromArray($styleJudul); $sheet->setCellValue('A3', 'Excel was generated on ' . date("Y-m-d H:i:s") . '');
 $sheet->mergeCells('A3:H3'); 
$sheet->getStyle('A3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

/**
* pada bagian set cell value ini diubah sesuai
*yang mau di tambahkan misal mau ditambahkan antara "Keterangan Absen" maka kolom yang H5 saat ini menjadi H6 dst
*atau mau diakhirnya boleh tinggal disesuaikan.
*/

 $sheet->setCellValue('A5', 'No'); 
$sheet->setCellValue('B5', 'Nama Pegawai'); 
$sheet->setCellValue('C5', 'Tanggal Absen'); 
$sheet->setCellValue('D5', 'Jam Datang'); 
$sheet->setCellValue('E5', 'Jam Pulang'); 
$sheet->setCellValue('F5', 'Status Kehadiran'); $sheet->setCellValue('G5', 'Keterangan Absen'); $sheet->setCellValue('H5', 'Titik Lokasi Maps'); 
$sheet->getStyle('A5:F5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER); $dataabsensi = $querydata; $no = 1; $rowx = 6; foreach ($dataabsensi as $rowabsen) { 

/**
* Untuk yang setCellValue ini sesuaikan dengan jenis kolom keterangannya pada sebelumnya
*Tambahkan setCellValue jika ada data yang ingin ditampilkan untuk di foreach
*
*/

$sheet->setCellValue('A' . $rowx, $no++); 
$sheet->setCellValue('B' . $rowx, $rowabsen->nama_pegawai); 
$sheet->setCellValue('C' . $rowx, $rowabsen->tgl_absen); 
$sheet->setCellValue('D' . $rowx, $rowabsen->jam_masuk); 
$sheet->setCellValue('E' . $rowx, (empty($rowabsen->jam_pulang)) ? 'Belum Absen Pulang' : $rowabsen->jam_pulang); $sheet->setCellValue('F' . $rowx, ($rowabsen->status_pegawai == 1) ? 'Sudah Absen' : (($rowabsen->status_pegawai == 2) ? 'Absen Terlambat' : 'Belum Absen')); 
$sheet->setCellValue('G' . $rowx, $rowabsen->keterangan_absen); 
$sheet->setCellValue('H' . $rowx, (empty($rowabsen->maps_absen)) ? 'Lokasi Tidak Ditemukan' : (($rowabsen->maps_absen == 'No Location') ? 'Lokasi Tidak Ditemukan' : $rowabsen->maps_absen)); $rowx++; }

/**
* Dan jangan lupa di set lebar kolomnya sesuai kebutuhan
* untuk kolom yang baru di tambahkan sebelumnya
*/ 
$spreadsheet->getActiveSheet()->getColumnDimension('A')->setWidth(5); 
$spreadsheet->getActiveSheet()->getColumnDimension('B')->setWidth(30); 
$spreadsheet->getActiveSheet()->getColumnDimension('C')->setWidth(28); 
$spreadsheet->getActiveSheet()->getColumnDimension('D')->setWidth(20); 
$spreadsheet->getActiveSheet()->getColumnDimension('E')->setWidth(20); 
$spreadsheet->getActiveSheet()->getColumnDimension('F')->setWidth(25); 
$spreadsheet->getActiveSheet()->getColumnDimension('G')->setWidth(38); 
$spreadsheet->getActiveSheet()->getColumnDimension('H')->setWidth(38);
```
- "**Docs.php**" untuk yang export _**PDF**_ itu ada di directory `views/layout/dataabsensi` disitu ada dua untuk yang layout PDF untuk exportnya yaitu **printallabsensi.php** dan yang untuk print **printselfabsensi.php**

Untuk yang **printallabsensi.php** bisa dimodif bagian ini
```
<table class="table">
 <thead>
 <tr>
 <th scope="col">No</th>
<th scope="col">Nama Pegawai</th>
<th scope="col">Tanggal Absen</th>
<th scope="col">Jam Datang</th> 
<th scope="col">Jam Pulang</th>
 <th scope="col">Status Kehadiran</th> 
<th scope="col">Keterangan Absen</th> 
<th scope="col">Titik Lokasi Maps</th>
 </tr> 
</thead>
 <tbody>
 <?php $no = 1; foreach ($dataabsensi as $absen) : ?>
 <tr> 
<th scope="row"><?= $no++; ?></th>
 <td><?= $absen->nama_pegawai; ?></td> <td><?= $absen->tgl_absen; ?></td> 
<td><?= $absen->jam_masuk; ?></td> <td><?= (empty($absen->jam_pulang)) ? 'Belum Absen Pulang' : $absen->jam_pulang; ?></td> <td><?= ($absen->status_pegawai == 1) ? 'Sudah Absen' : (($absen->status_pegawai == 2) ? 'Absen Terlambat' : 'Belum Absen'); ?></td>
 <td><?= $absen->keterangan_absen; ?></td> 
<td><?= (empty($absen->maps_absen)) ? 'Lokasi Tidak Ditemukan' : (($absen->maps_absen == 'No Location') ? 'Lokasi Tidak Ditemukan' : $absen->maps_absen); ?></td>
 </tr> 
<?php endforeach; ?> 
</tbody>
 </table>
```

Untuk yang **printselfabsensi.php** bisa dimodif bagian ini untuk ditambahkan rownya menggunakan `<dd></dd> dan <dt></dt>` seperti yang lainnya
```
<div class="row detail"> 
<div class="col-md-10 col-sm-8 col-6">
 <dl class="row">
 <dt class="col-sm-5">Nama Pegawai:</dt> <dd class="col-sm-7"><?= $dataabsensi['nama_pegawai'] ?></dd>
 <dt class="col-sm-5">Tanggal Absen:</dt> <dd class="col-sm-7"><?= $dataabsensi['tgl_absen'] ?></dd>
 <dt class="col-sm-5">Waktu Datang:</dt> <dd class="col-sm-7"><?= $dataabsensi['jam_masuk'] ?></dd> 
<dt class="col-sm-5">Waktu Pulang:</dt> <dd class="col-sm-7"><?= (empty($dataabsensi['jam_pulang'])) ? 'Belum Absen Pulang' : $dataabsensi['jam_pulang']; ?></dd> <dt class="col-sm-5">Status Kehadiran:</dt> <dd class="col-sm-7"><?= ($dataabsensi['status_pegawai'] == 1) ? 'Sudah Absen' : (($dataabsensi['status_pegawai'] == 2) ? 'Absen Terlambat' : 'Belum Absen'); ?></dd> 
<dt class="col-sm-5">Keterangan Absen:</dt><dd class="col-sm-7"><?= $dataabsensi['keterangan_absen'] ?></dd> 
<dt class="col-sm-5">Titik Lokasi Maps:</dt> <dd class="col-sm-7"><?= (empty($dataabsensi['maps_absen'])) ? 'Lokasi Tidak Ditemukan' : (($dataabsensi['maps_absen'] == 'No Location') ? 'Lokasi Tidak Ditemukan' : $dataabsensi['maps_absen']); ?></dd> 
</dl>
 </div> 
</div>
```

4. Untuk helper sepertinya tidak perlu di modif ulang

Mungkin kurang lebihnya seperti itu kalau untuk bagian yang yang perlu di ubah kalau mau di modif

Oh iya saya minta maaf tadi threadnya ke closed Issue karena kepecet 😅🙏🏻

**Comment by sandyh90** [comment]
__

**Comment by ayahaceh** [comment]
Terimakasih banyak, mas.. atas responnya.
1. Ini saya coba opsi pertama saja, yaitu nambahin kolom pada tabel yang sudah ada saja (db_absensi),
2. Terus ada yang menarik disini, yaitu penggunaan id random 5 digit, ide yang cemerlang untuk mengisi kolom id. Tetapi saat absensinya sudah berjalan tahunan, apakah ini aman? dalam arti tidak akan ada generate id yang sama (doube) nantinya?

Nanti kalau uda selesai, akan saya publish di repo juga rencananya (public).

**Comment by sandyh90** [comment]
iya sama - sama mas, kalau untuk masalah id absennya ke double misalnya ada id "**23942**" terus yang ke input id yang sama "**23942**" ini juga saya masih ragukan soalnya walaupun idnya random namanya sistem pasti bisa ke regenerate ulang dan juga aplikasi ini belum dicoba untuk berjalan selama setahun dan pada bagian ini juga harus cukup di perhatikan untuk jaga - jaga mencegah terjadinya double id, mas boleh modif ulang untuk yang id random 5 digit itu untuk disesuaikan dengan kebutuhan tetapi kalau untuk sekarang sepertinya aman untuk yang id random itu.
