### ISSUE TITLE
Real-time waktu absensi

### ISSUE THREAD

**Issue by KamaludinZ** [sandyh90/Codeigniter3-absen-digital#6]
Ketika melakukan absen pertama tidak ada masalah. Di hari kedua terjadi kendala : tanggal tetap mengikuti hari sebelumnya padahal sudah berganti hari, untuk jam sudah sesuai.
Dihari ketiga : tidak bisa melakukan absen karena jam datang dan pulang masih menampilkan hari sebelumnya dan tidak reset kembali di setiap esok harinya.

![Screenshot_2021-07-02-10-04-39-87](https://user-images.githubusercontent.com/63649095/124215432-333bf000-db1e-11eb-96eb-6d1bd37c734e.jpg)

**Comment by sandyh90** [comment]
sepertinya untuk masalah ini nanti saya akan coba testing terlebih dahulu di server local karena ini juga harus dilihat dulu takutnya logika saat absennya ada yang keubah, terima kasih banyak mas untuk masalah bug ini mudah - mudahan bisa diperbaiki segera

**Comment by sandyh90** [comment]
saya sudah coba tetapi anehnya waktunya yang dipakai sudah real-time

List Absen Sebelum Mencoba Absen Sekarang
![Capture 1](https://user-images.githubusercontent.com/30236529/124220523-23290e00-db28-11eb-8631-12e4b819c5c5.PNG)

Sebelum Mencoba Absen Sekarang
![Capture 2](https://user-images.githubusercontent.com/30236529/124220527-258b6800-db28-11eb-88e5-82d09fe61fc1.PNG)

List Absen Setelah Mencoba Absen Sekarang
![Capture 3](https://user-images.githubusercontent.com/30236529/124220783-9f235600-db28-11eb-9515-b8580d82bb3c.PNG)

Setelah Mencoba Absen Sekarang
![Capture 4](https://user-images.githubusercontent.com/30236529/124220790-a185b000-db28-11eb-9c74-39717b041b53.PNG)

ini yang saya curiga adalah dibagian timezonenya ke override sama yang bawaan punya php jadi dia pakainya bukan zona waktunya indonesia coba mas buka di php.ini cari dan diubah pada bagian seperti ini

```
[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = Asia/Jakarta
```

atau di "**index.php**" tambahin seperti ini

`date_default_timezone_set('Asia/Jakarta');`

seperti ini diatas komentar dari codeigniternya
![Capture index php](https://user-images.githubusercontent.com/30236529/124221535-2cb37580-db2a-11eb-8413-63da7eef308b.png)
