### ISSUE TITLE
Jika User shift/kerja 12 jam untuk absen pulangnya bagaimana?

### ISSUE THREAD

**Issue by zero84** [sandyh90/Codeigniter3-absen-digital#8]

**Comment by sandyh90** [comment]
Hmm untuk masalah ini kayaknya harus ada yang diubah dibagian ajax logika absennya mungkin nanti saya pikirkan kembali dan akan perbaiki lagi agar bisa absen sesuai tipe status kerja dari masing - masing user jika user tersebut dalam tipe bagian shift.
